#!/usr/bin/env python3
"""
Generate cloudflare/src/registryConstants.generated.ts from Python completion targets / origins.

Run from repo root after editing origins.py or completion_targets.py:
  python scripts/gen_registry_constants_ts.py
"""
from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def main() -> None:
    import sys

    sys.path.insert(0, str(REPO))
    from src.knowledge.blend_depth import SOUND_ORIGIN_PRIMITIVES
    from src.knowledge.completion_targets import (
        DYNAMIC_CANONICAL,
        ENTITY_ESTIMATED_CELLS,
        NARRATIVE_ORIGIN_SIZES,
        STATIC_COLOR_ESTIMATED_CELLS,
        STATIC_SOUND_NUM_PRIMITIVES,
    )

    out = REPO / "cloudflare" / "src" / "registryConstants.generated.ts"
    narrative = json.dumps(NARRATIVE_ORIGIN_SIZES, indent=2)
    canonical = json.dumps(DYNAMIC_CANONICAL, indent=2)
    sound = json.dumps(list(SOUND_ORIGIN_PRIMITIVES))

    body = f"""// AUTO-GENERATED by scripts/gen_registry_constants_ts.py — do not edit by hand.
// Source: src/knowledge/completion_targets.py + origins.py + blend_depth.py

export const STATIC_COLOR_ESTIMATED_CELLS = {STATIC_COLOR_ESTIMATED_CELLS};

export const STATIC_SOUND_NUM_PRIMITIVES = {STATIC_SOUND_NUM_PRIMITIVES};

export const ENTITY_ESTIMATED_CELLS = {ENTITY_ESTIMATED_CELLS};

export const SOUND_ORIGIN_PRIMARIES = {sound} as const;

export const NARRATIVE_ORIGIN_SIZES: Record<string, number> = {narrative};

/** Full origin taxonomies for registries UI + coverage (mission-aligned). */
export const DYNAMIC_CANONICAL = {canonical} as const;
"""
    out.write_text(body, encoding="utf-8")
    print(f"Wrote {out}")
    print(f"  narrative aspects: {NARRATIVE_ORIGIN_SIZES}")
    print(f"  sound primitives: {STATIC_SOUND_NUM_PRIMITIVES}")
    print(f"  entity cells: {ENTITY_ESTIMATED_CELLS}")
    print(f"  audio moods: {len(DYNAMIC_CANONICAL['sound_mood'])}")


if __name__ == "__main__":
    main()
