#!/usr/bin/env python3
"""
Generate cloudflare/src/colorPrimaries.generated.ts from src/knowledge/static_registry.py.
Run from repo root after editing STATIC_COLOR_PRIMITIVES.
"""
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PY = REPO / "src/knowledge/static_registry.py"
OUT = REPO / "cloudflare" / "src" / "colorPrimaries.generated.ts"


def main() -> None:
    src = PY.read_text(encoding="utf-8")
    pat = re.compile(r"_rgb\((\d+),\s*(\d+),\s*(\d+)\),\s*#\s*(.+)")
    primaries: list[tuple[str, int, int, int]] = []
    name_aliases: set[str] = set()
    seen_rgb: set[tuple[int, int, int]] = set()
    for m in pat.finditer(src):
        r, g, b = int(m.group(1)), int(m.group(2)), int(m.group(3))
        comment = m.group(4).strip()
        if (r, g, b) in seen_rgb:
            continue
        seen_rgb.add((r, g, b))
        # Primary display name: first segment before /
        first_seg = comment.split("/")[0].strip()
        primary = re.sub(r"[^a-z0-9]", "", first_seg.split()[0].lower()) if first_seg else "color"
        primaries.append((primary, r, g, b))
        for part in re.split(r"[/,]", comment):
            w = re.sub(r"[^a-z0-9]", "", part.strip().split()[0].lower()) if part.strip() else ""
            if w and len(w) > 1:
                name_aliases.add(w)

    lines = [
        "// AUTO-GENERATED by scripts/gen_color_primaries_ts.py — do not edit by hand.",
        "",
        "export const COLOR_PRIMARIES_FOR_API: ReadonlyArray<{ name: string; r: number; g: number; b: number }> = [",
    ]
    for name, r, g, b in primaries:
        lines.append(f'  {{ name: "{name}", r: {r}, g: {g}, b: {b} }},')
    lines.append("];")
    lines.append("")
    lines.append("/** All known primitive color names (for depth_breakdown classification). */")
    lines.append("export const COLOR_PRIMITIVE_NAMES = new Set<string>([")
    for n in sorted(name_aliases):
        lines.append(f'  "{n}",')
    lines.append("]);")
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(primaries)} primaries, {len(name_aliases)} name aliases -> {OUT}")


if __name__ == "__main__":
    main()
