// AUTO-GENERATED by scripts/gen_registry_constants_ts.py — do not edit by hand.
// Source: src/knowledge/completion_targets.py + origins.py + blend_depth.py

export const STATIC_COLOR_ESTIMATED_CELLS = 27951;

export const STATIC_SOUND_NUM_PRIMITIVES = 10;

export const ENTITY_ESTIMATED_CELLS = 56;

export const SETTING_ESTIMATED_CELLS = 19;

export const SETTING_PRIMITIVES = ["city", "neon", "ocean", "beach", "underwater", "forest", "night", "noir", "golden_hour", "day", "desert", "mountain", "space", "studio", "interior", "exterior", "rain", "moody", "abstract"] as const;

export const SOUND_ORIGIN_PRIMARIES = ["silence", "rumble", "hum", "tone", "hiss", "rustle", "thump", "click", "whoosh", "drip"] as const;

export const NARRATIVE_ORIGIN_SIZES: Record<string, number> = {
  "genre": 24,
  "mood": 20,
  "style": 11,
  "plots": 4,
  "settings": 25,
  "themes": 25,
  "scene_type": 17
};

/** Full origin taxonomies for registries UI + coverage (mission-aligned). */
export const DYNAMIC_CANONICAL = {
  "gradient_type": [
    "vertical",
    "horizontal",
    "radial",
    "angled"
  ],
  "camera_motion": [
    "static",
    "pan",
    "tilt",
    "dolly",
    "crane",
    "zoom",
    "zoom_out",
    "handheld",
    "roll",
    "truck",
    "pedestal",
    "arc",
    "tracking",
    "birds_eye",
    "whip_pan",
    "rotate"
  ],
  "motion_speed": [
    "static",
    "slow",
    "medium",
    "fast"
  ],
  "motion_rhythm": [
    "steady",
    "pulsing",
    "wave",
    "random"
  ],
  "motion_smoothness": [
    "jerky",
    "rough",
    "smooth",
    "fluid"
  ],
  "motion_directionality": [
    "none",
    "horizontal",
    "vertical",
    "diagonal",
    "radial"
  ],
  "motion_acceleration": [
    "constant",
    "ease_in",
    "ease_out",
    "ease_in_out"
  ],
  "motion": [
    "static",
    "slow",
    "medium",
    "fast",
    "steady",
    "pulsing",
    "wave",
    "random"
  ],
  "sound_tempo": [
    "slow",
    "medium",
    "fast"
  ],
  "sound_mood": [
    "neutral",
    "calm",
    "tense",
    "uplifting",
    "dark",
    "dramatic",
    "peaceful",
    "chaotic",
    "soft",
    "harsh",
    "dreamy",
    "bright",
    "energetic",
    "moody",
    "melancholy",
    "intense",
    "playful",
    "suspenseful",
    "hopeful",
    "ominous"
  ],
  "sound_presence": [
    "silence",
    "ambient",
    "music",
    "sfx",
    "full"
  ],
  "sound": [
    "tempo: slow",
    "tempo: medium",
    "tempo: fast",
    "mood: neutral",
    "mood: calm",
    "mood: tense",
    "mood: uplifting",
    "mood: dark",
    "mood: dramatic",
    "mood: peaceful",
    "mood: chaotic",
    "mood: soft",
    "mood: harsh",
    "mood: dreamy",
    "mood: bright",
    "mood: energetic",
    "mood: moody",
    "mood: melancholy",
    "mood: intense",
    "mood: playful",
    "mood: suspenseful",
    "mood: hopeful",
    "mood: ominous",
    "presence: silence",
    "presence: ambient",
    "presence: music",
    "presence: sfx",
    "presence: full"
  ],
  "entity_kind": [
    "circle",
    "rect",
    "arrow",
    "character"
  ],
  "entity_trajectory": [
    "left",
    "right",
    "up",
    "down",
    "toward",
    "away",
    "none"
  ],
  "expression": [
    "neutral",
    "happy",
    "sad",
    "angry",
    "calm",
    "excited",
    "nervous"
  ],
  "personality": [
    "neutral",
    "playful",
    "serious",
    "energetic",
    "shy",
    "confident"
  ],
  "gag": [
    "none",
    "squash",
    "spin",
    "wink",
    "flourish",
    "double_take"
  ],
  "setting": [
    "city",
    "neon",
    "ocean",
    "beach",
    "underwater",
    "forest",
    "night",
    "noir",
    "golden_hour",
    "day",
    "desert",
    "mountain",
    "space",
    "studio",
    "interior",
    "exterior",
    "rain",
    "moody",
    "abstract"
  ]
} as const;
